### ISSUE TITLE
Add ldc (D) compiler

### ISSUE THREAD

**Issue by rikkimax** [dyu/ffi-overhead#5]
While dmd does generate reasonable code, dmd's backend isn't exactly this century (even though it does very well).

For a better comparison against C++ with gcc, it would be best to use ldc (maybe even gdc?) as well.

**Comment by dyu** [comment]
Could you create a pull request with the ldc variant?

**Comment by rikkimax** [comment]
It'll need testing which I can't really do without a lot of work.

Two changes from what I can see:

- ``dmd`` into ``ldc2``
- ``-O into ``-O3``

And maybe add the flag ``-boundscheck=off``.

**Comment by dyu** [comment]
Added the ldc2 variant and updated the results.
The `-release` flag is already on.  The `-boundscheck=off` didn't affect the results.

Thanks!
